import * as alphaTab from '@coderline/alphatab';
const score = new alphaTab.model.Score();
score.title = 'Smoke';
const mb = new alphaTab.model.MasterBar();
score.addMasterBar(mb);
const track = new alphaTab.model.Track();
const staff = new alphaTab.model.Staff();
const bar = new alphaTab.model.Bar();
const voice = new alphaTab.model.Voice();
const beat = new alphaTab.model.Beat();
beat.isEmpty = true;
voice.addBeat(beat); bar.addVoice(voice); staff.addBar(bar);
track.addStaff(staff); score.addTrack(track);
const settings = new alphaTab.Settings();
score.finish(settings);
const data = new alphaTab.exporter.Gp7Exporter().export(score, settings);
console.log('exported bytes:', data.byteLength);
const re = alphaTab.importer.ScoreLoader.loadScoreFromBytes(data, settings);
console.log('reimported title:', re.title, 'tracks:', re.tracks.length);
